AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  describeEC21: 
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://numair
      Handler: calc.calc
      Runtime: python3.8
      Role: "arn:aws:iam::712841247589:role/lambdaRole"


      
